text = open('/home/lym/testpyth')
read_text = text.read()
text.close()
text = open('/home/lym/pyth2', 'w')
text.write(read_text)
text.close()
text = open('/home/lym/pyth2')
#read = text.read()
print(text.read())
